version: 2
registries:
  docker.io:
    type : docker-registry
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    url: https://index.docker.io/v1/
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

      