name: CI

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
jobs:

  validate: ## pour valider la syntaxe des fichiers de configuration et la validité du docker-compose
    name: Validate repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate YAML files
        uses: rhysd/actionlint@v1.7.12
    
      - name: Validate Docker Compose file
        run: docker compose -f docker-compose.yml config -q

  sast: ## pour analyser le code source à la recherche de vulnérabilités
    name: sonarqube scan
    runs-on: ubuntu-latest
    needs: validate
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SonarQube scan
        uses: sonarsource/sonarcloud-github-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN }}
      - name: Check SonarQube quality gate
        uses: sonarsource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN }}
  
  trivy: ## pour scanner les images à la recherche de vulnérabilités
    name: Trivy scan image
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "image"
          image-ref: "vulnerables/web-dvwa:1.9"
          format: "json"
          output: "trivy-report.json"
          severity: "HIGH,CRITICAL"
          exit-code: 1

      - name: Upload Trivy report
        uses: actions/upload-artifact@v7.0.1
        with:
          name: trivy-report
          path: trivy-report.json

  sbom:  ##pour lister les dépendances d'une image 
    name: Generate SBOM
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "sbom"
          image-ref: "vulnerables/web-dvwa:1.9"
          format: "cyclonedx"
          output: "sbom.json"
      - name: Upload SBOM
        uses: actions/upload-artifact@v7.0.1
        with:
          name: sbom
          path: sbom.json
          

  